/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bangun_datar;

/**
 *
 * @author acer
 */
public class frameDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frameDashboard.class.getName());

    /**
     * Creates new form frameDashboard
     */
    public frameDashboard() {
        initComponents();
        
        //menambahkan margin untuk card dengan panel
        panelCard.setBorder(
        javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15)
        );
        
        
        //membuat agar warna border di tiap card dan bisa disesuaikan 
        ((RoundedPanel) panelSegitiga).setBorderColor(
            new java.awt.Color(33, 150, 243)
        );

        ((RoundedPanel) panelPersegi).setBorderColor(
            new java.awt.Color(255, 152, 0)
        );

        ((RoundedPanel) panelPersegiPanjang).setBorderColor(
            new java.awt.Color(76, 175, 80)
        );

        ((RoundedPanel) panelLingkaran).setBorderColor(
            new java.awt.Color(156, 39, 176)
        );

        ((RoundedPanel) panelJajarGenjang).setBorderColor(
            new java.awt.Color(0, 188, 212)
        );

        ((RoundedPanel) panelBelahKetupat).setBorderColor(
            new java.awt.Color(0, 188, 212)
        );
//         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        panelLogo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelJudul = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelIsi = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelCard = new javax.swing.JPanel();
        panelSegitiga = new RoundedPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelPersegi = new RoundedPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelPersegiPanjang = new RoundedPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelLingkaran = new RoundedPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelJajarGenjang = new RoundedPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelBelahKetupat = new RoundedPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelFooter = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard Bangun Datar");

        panelUtama.setBackground(new java.awt.Color(209, 242, 255));
        panelUtama.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));
        panelUtama.setName("panelUtama"); // NOI18N
        panelUtama.setLayout(new java.awt.BorderLayout(5, 10));

        panelHeader.setPreferredSize(new java.awt.Dimension(900, 170));
        panelHeader.setLayout(new java.awt.BorderLayout());

        panelLogo.setBackground(new java.awt.Color(209, 242, 255));
        panelLogo.setPreferredSize(new java.awt.Dimension(150, 160));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bangun_datar/img/beranda2.png"))); // NOI18N
        panelLogo.add(jLabel4);

        panelHeader.add(panelLogo, java.awt.BorderLayout.LINE_START);

        panelJudul.setBackground(new java.awt.Color(209, 242, 255));
        panelJudul.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(209, 242, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setForeground(javax.swing.UIManager.getDefaults().getColor("CheckBox.icon[filled].pressedSelectedBackground"));
        jLabel2.setText("BERANDA ");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(javax.swing.UIManager.getDefaults().getColor("CheckBox.icon[filled].pressedSelectedBackground"));
        jLabel3.setText("KALKULATOR BANGUN DATAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelJudul.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(209, 242, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 60));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 954, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        panelJudul.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        panelHeader.add(panelJudul, java.awt.BorderLayout.CENTER);

        panelUtama.add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelIsi.setBackground(new java.awt.Color(209, 242, 255));
        panelIsi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, java.awt.Color.cyan));
        panelIsi.setPreferredSize(new java.awt.Dimension(900, 550));
        panelIsi.setLayout(new java.awt.BorderLayout(15, 15));

        jLabel5.setBackground(new java.awt.Color(209, 242, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PILIH BANGUN DATAR UNTUK DIHITUNG LUAS DAN KELILING NYA");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setIconTextGap(15);
        jLabel5.setPreferredSize(new java.awt.Dimension(386, 40));
        panelIsi.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        panelCard.setPreferredSize(new java.awt.Dimension(860, 400));
        panelCard.setLayout(new java.awt.GridLayout(2, 3, 20, 15));

        panelSegitiga.setBackground(new java.awt.Color(193, 228, 255));
        panelSegitiga.setPreferredSize(new java.awt.Dimension(150, 120));
        panelSegitiga.setLayout(new java.awt.BorderLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bangun_datar/img/SEGITIGAA.png"))); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 20));
        panelSegitiga.add(jLabel7, java.awt.BorderLayout.CENTER);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SEGITIGA");
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 60));
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panelSegitiga.add(jLabel8, java.awt.BorderLayout.PAGE_END);

        panelCard.add(panelSegitiga);

        panelPersegi.setBackground(new java.awt.Color(255, 229, 178));
        panelPersegi.setPreferredSize(new java.awt.Dimension(150, 120));
        panelPersegi.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bangun_datar/img/PERSEGI.png"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 20));
        panelPersegi.add(jLabel6, java.awt.BorderLayout.CENTER);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PERSEGI");
        jLabel10.setPreferredSize(new java.awt.Dimension(150, 60));
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        panelPersegi.add(jLabel10, java.awt.BorderLayout.PAGE_END);

        panelCard.add(panelPersegi);

        panelPersegiPanjang.setBackground(new java.awt.Color(230, 255, 229));
        panelPersegiPanjang.setPreferredSize(new java.awt.Dimension(150, 120));
        panelPersegiPanjang.setLayout(new java.awt.BorderLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bangun_datar/img/PERSEGI PANJANG.png"))); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(150, 20));
        panelPersegiPanjang.add(jLabel12, java.awt.BorderLayout.CENTER);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PERSEGI PANJANG");
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 60));
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panelPersegiPanjang.add(jLabel9, java.awt.BorderLayout.PAGE_END);

        panelCard.add(panelPersegiPanjang);

        panelLingkaran.setBackground(new java.awt.Color(227, 203, 255));
        panelLingkaran.setPreferredSize(new java.awt.Dimension(150, 120));
        panelLingkaran.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("LINGKARAN");
        jLabel11.setPreferredSize(new java.awt.Dimension(150, 60));
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panelLingkaran.add(jLabel11, java.awt.BorderLayout.PAGE_END);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bangun_datar/img/LINGKARAN.png"))); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(150, 20));
        panelLingkaran.add(jLabel13, java.awt.BorderLayout.CENTER);

        panelCard.add(panelLingkaran);

        panelJajarGenjang.setBackground(new java.awt.Color(209, 242, 255));
        panelJajarGenjang.setPreferredSize(new java.awt.Dimension(150, 120));
        panelJajarGenjang.setLayout(new java.awt.BorderLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bangun_datar/img/JAJAR GENJANG.png"))); // NOI18N
        jLabel15.setPreferredSize(new java.awt.Dimension(150, 20));
        panelJajarGenjang.add(jLabel15, java.awt.BorderLayout.CENTER);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("JAJAR GENJANG");
        jLabel14.setPreferredSize(new java.awt.Dimension(150, 60));
        jLabel14.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panelJajarGenjang.add(jLabel14, java.awt.BorderLayout.PAGE_END);

        panelCard.add(panelJajarGenjang);

        panelBelahKetupat.setBackground(new java.awt.Color(224, 255, 253));
        panelBelahKetupat.setLayout(new java.awt.BorderLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("BELAH KETUPAT");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel16.setPreferredSize(new java.awt.Dimension(150, 60));
        panelBelahKetupat.add(jLabel16, java.awt.BorderLayout.PAGE_END);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bangun_datar/img/BELAH KETUPAT.png"))); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(150, 20));
        panelBelahKetupat.add(jLabel17, java.awt.BorderLayout.CENTER);

        panelCard.add(panelBelahKetupat);

        panelIsi.add(panelCard, java.awt.BorderLayout.CENTER);

        panelFooter.setBackground(new java.awt.Color(209, 242, 255));
        panelFooter.setPreferredSize(new java.awt.Dimension(900, 50));

        jButton1.setText("Keluar");

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFooterLayout.createSequentialGroup()
                .addContainerGap(1010, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFooterLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        panelIsi.add(panelFooter, java.awt.BorderLayout.PAGE_END);

        panelUtama.add(panelIsi, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelUtama, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        frameYakin persegi = new frameYakin();
        persegi.setLocationRelativeTo(null);
        persegi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        com.formdev.flatlaf.FlatLightLaf.setup();

        java.awt.EventQueue.invokeLater(() -> {
            new frameDashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelBelahKetupat;
    private javax.swing.JPanel panelCard;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelIsi;
    private javax.swing.JPanel panelJajarGenjang;
    private javax.swing.JPanel panelJudul;
    private javax.swing.JPanel panelLingkaran;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelPersegi;
    private javax.swing.JPanel panelPersegiPanjang;
    private javax.swing.JPanel panelSegitiga;
    private javax.swing.JPanel panelUtama;
    // End of variables declaration//GEN-END:variables
}
